apiVersion: v1
kind: Service
metadata:
  name: cart-service
  namespace: default
  labels:
    app: cart
spec:
  type: ClusterIP
  selector:
    app: cart
  ports:
  - name: http
    port: 3002
    targetPort: 3003
    protocol: TCP
  sessionAffinity: None
